"""Report generators for completed Q&A sessions."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from .models import Answer, Section, Session


def _section_answers(section: Section, answers: dict[str, Answer]) -> list[Answer]:
    """Return answers belonging to a section, preserving question order."""
    result: list[Answer] = []
    for q in section.questions:
        if q.id in answers:
            result.append(answers[q.id])
    return result


def _format_value(value: Any) -> str:
    """Format an answer value for display."""
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    return str(value)


def generate_markdown_report(session: Session) -> str:
    """Generate a formatted markdown requirements document from session answers."""
    now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []

    lines.append(f"# {session.topic}")
    lines.append("")
    lines.append(f"**Template:** {session.template.name}  ")
    lines.append(f"**Date:** {now}  ")
    lines.append(f"**Session:** {session.id}  ")
    lines.append(f"**Completion:** {session.progress_pct}%")
    lines.append("")
    lines.append("---")
    lines.append("")

    for section in session.template.sections:
        section_answers = _section_answers(section, session.answers)
        section_notes = [n for n in session.notes if n.section_id == section.id]
        if not section_answers and not section_notes:
            continue

        lines.append(f"## {section.title}")
        lines.append("")

        for answer in section_answers:
            lines.append(f"**{answer.question_text}**  ")
            lines.append(_format_value(answer.value))
            lines.append("")

        if section_notes:
            lines.append("**Additional Notes**")
            lines.append("")
            for note in section_notes:
                lines.append(f"- {note.text}")
            lines.append("")

    # Notes not attached to any section
    general_notes = [n for n in session.notes if n.section_id is None]
    if general_notes:
        lines.append("## Additional Notes")
        lines.append("")
        for note in general_notes:
            lines.append(f"- {note.text}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by Amplifier Q&A*")
    lines.append("")

    return "\n".join(lines)


def generate_json_report(session: Session) -> dict[str, Any]:
    """Generate a structured JSON report from session answers."""
    now = datetime.now(tz=timezone.utc).isoformat()

    sections_out: list[dict[str, Any]] = []
    for section in session.template.sections:
        section_answers = _section_answers(section, session.answers)
        section_notes = [n for n in session.notes if n.section_id == section.id]
        if not section_answers and not section_notes:
            continue
        entry: dict[str, Any] = {
            "id": section.id,
            "title": section.title,
            "answers": [
                {
                    "question_id": a.question_id,
                    "question": a.question_text,
                    "answer": a.value,
                }
                for a in section_answers
            ],
        }
        if section_notes:
            entry["notes"] = [n.text for n in section_notes]
        sections_out.append(entry)

    general_notes = [n for n in session.notes if n.section_id is None]

    result: dict[str, Any] = {
        "topic": session.topic,
        "template": session.template.id,
        "template_name": session.template.name,
        "timestamp": now,
        "session_id": session.id,
        "completion_pct": session.progress_pct,
        "sections": sections_out,
    }
    if general_notes:
        result["notes"] = [n.text for n in general_notes]

    return result
